name: Python package

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
    
jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Run tests
      - name: Run tests
        run: |
          cd src
          python -m pytest addition.py